# Generated by Django 3.2 on 2021-04-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Montly_Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('month', models.CharField(choices=[('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('APRIL', 'April'), ('MAY', 'May'), ('JUNE', 'June'), ('JULY', 'July'), ('AUGUST', 'August'), ('SEPTEMBER', 'September'), ('OCTOBER', 'October'), ('NOVEMBER', 'November'), ('DECEMBER', 'December')], default='JANUARY', max_length=20, null=True)),
                ('description', models.CharField(max_length=80, null=True)),
                ('amount', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='register',
            name='data_of_birth',
        ),
        migrations.RemoveField(
            model_name='register',
            name='gender',
        ),
    ]
