# Generated by Django 3.2 on 2021-04-18 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_auto_20210418_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='montly_expenses',
            name='month',
        ),
    ]
