# Generated by Django 3.2 on 2021-04-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0003_remove_montly_expenses_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montly_expenses',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
