# Generated by Django 3.2 on 2021-04-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0004_alter_montly_expenses_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montly_expenses',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
