# Generated by Django 3.2 on 2021-04-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0007_auto_20210419_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='montly_expenses',
            old_name='customer',
            new_name='register',
        ),
    ]
