# Generated by Django 3.2 on 2021-04-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0009_remove_montly_expenses_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='montly_expenses',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
