# Generated by Django 3.2 on 2021-04-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0011_alter_montly_expenses_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='montly_expenses',
            old_name='name',
            new_name='customer',
        ),
    ]
